name: 'PR'

on:
  workflow_dispatch: {}
  pull_request:
    branches:
    - main

jobs:
  ci:
    name: CI
    uses: nu12/templates/.github/workflows/go-pr.yml@main
    with:
      run-lint: true
      run-test: true
      run-docker-build: false
      go-version: '1.23.6'
      docker-tag: 'latest'
    secrets: inherit
